name: Testes APIs Públicas com Jest e Supertest

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Jest-tests-Modelo-Whitebox:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install modules
        run: npm install
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install modules
        run: npm install
      - name: Run white box tests 🧪
        run: npm run jest